import pandas as pd
import matplotlib.pyplot as plt


# Set dark theme for better visibility
plt.style.use('dark_background')

# Read the CSV file generated by the C++ program
df = pd.read_csv('process_schedule.csv')

# Create figure with dark background
fig, ax = plt.subplots(figsize=(12, 6), facecolor='#1c1c1c')

# High-contrast color palette for visibility
high_contrast_colors = [
    '#ff0000', '#00ff00', '#ffff00', '#00ffff',
    '#ff00ff', '#ffa500', '#7fff00', '#ff69b4'
]


# Plot each process execution as a horizontal bar
# Each row in CSV represents one execution episode

for _,row  in df.iterrows():
    ax.hlines(
        y = row['pid'],
        xmin = row['start_time'],
        xmax= row['start_time'],
        linewidth=10,
        color=high_contrast_colors[row['pid'] % len(high_contrast_colors)]
    )



# Customize Plot appearance
ax.set_title('Process Schedule Timeline', color='white', fontsize=14, pad=20)
ax.set_xlabel('Time (nanoseconds)', color='white', fontsize=12)
ax.set_ylabel('Process ID', color='white', fontsize=12)

# Add grid for readability
ax.grid(True, axis='x', linestyle='--', alpha=0.4, color='#a0a0a0')


# Configure y-axis to show process IDs
unique_pids = df['pid'].unique()
ax.set_yticks(unique_pids)
ax.tick_params(axis='both', colors='white')


# Save the plot
plt.tight_layout()
plt.savefig('process_schedule_dark.png', facecolor=fig.get_facecolor(), dpi=300)
print("Visualization saved to process_schedule_dark.png")


